version: 2.0
commands:
   sayhello:
     description: "command for demonstration purposes"
     parameters:
      to:
        type: string
        default: "Hello World"
     steps:
      - run: echo << parameters.to >>
jobs:
  build:
    docker:
      - image: centos
    steps:
      - checkout
      - run: echo "Hello World"
      - sayhello:
          to: "Lev"
